CREATE TABLE public.bipol_tracker (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    bus_id text NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    speed double precision DEFAULT 0,
    gas_level integer DEFAULT 0
);

ALTER TABLE public.bipol_tracker ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.bipol_tracker
AS PERMISSIVE FOR SELECT
TO public
USING (true);

CREATE POLICY "Enable insert for all users" ON public.bipol_tracker
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);