CREATE TABLE IF NOT EXISTS public.bipol_tracker (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    bus_id text,
    latitude double precision,
    longitude double precision,
    speed double precision,
    gas_level integer
);

ALTER TABLE public.bipol_tracker DISABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_bipol_tracker_bus_id ON public.bipol_tracker(bus_id);
CREATE INDEX IF NOT EXISTS idx_bipol_tracker_created_at ON public.bipol_tracker(created_at DESC);