
DROP TABLE IF EXISTS admin_users CASCADE;

CREATE TABLE admin_users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

INSERT INTO admin_users (username, password_hash)
VALUES ('admin', '$2b$10$GF9VCWQVGzjebQt0FDUGte/KBWGp26q2eRI2C/p8PpkSIv0M4iP4u');
