-- 2. BIPOL TRACKER SCHEMA
DROP TABLE IF EXISTS bipol_tracker CASCADE;

CREATE TABLE bipol_tracker (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    bus_id text,
    latitude float,
    longitude float,
    speed float,
    gas_level int
);

ALTER TABLE bipol_tracker DISABLE ROW LEVEL SECURITY;
