-- 3. APP INFO SCHEMA
DROP TABLE IF EXISTS app_info CASCADE;

CREATE TABLE app_info (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE app_info ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON app_info;
CREATE POLICY "Enable read access for all users" ON app_info FOR SELECT USING (true);

DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON app_info;
CREATE POLICY "Enable insert for authenticated users only" ON app_info FOR INSERT WITH CHECK (true);
