-- 4. GEOFENCES & EVENTS SCHEMA
DROP TABLE IF EXISTS geofence_events CASCADE;
DROP TABLE IF EXISTS geofences CASCADE;

CREATE TABLE geofences (
    id bigint generated by default as identity primary key,
    name text not null,
    latitude double precision not null,
    longitude double precision not null,
    radius_meters integer default 100,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE geofence_events (
    id bigint generated by default as identity primary key,
    bus_id text not null,
    geofence_id bigint references geofences(id),
    event_type text not null,
    timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Default Geofences
INSERT INTO geofences (name, latitude, longitude, radius_meters)
VALUES 
('Halte PNJ', -6.372132, 106.824248, 150),
('Garasi / Pool', -6.368864, 106.833098, 200)
ON CONFLICT DO NOTHING;

ALTER TABLE geofences ENABLE ROW LEVEL SECURITY;
ALTER TABLE geofence_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Read Zones" ON geofences;
CREATE POLICY "Public Read Zones" ON geofences FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public Read Events" ON geofence_events;
CREATE POLICY "Public Read Events" ON geofence_events FOR SELECT USING (true);
