
DROP TABLE IF EXISTS lost_items CASCADE;

CREATE TABLE lost_items (
    id bigint generated by default as identity primary key,
    bus_plate text not null,
    whatsapp_number text not null,
    message text not null,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE lost_items DISABLE ROW LEVEL SECURITY;
