
DROP TABLE IF EXISTS feedback CASCADE;

CREATE TABLE feedback (
    id bigint generated by default as identity primary key,
    name text,
    message text not null,
    status text default 'pending',
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE feedback DISABLE ROW LEVEL SECURITY;
