create table if not exists admin_users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE TABLE IF NOT EXISTS bipol_tracker (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    bus_id text,
    latitude float,
    longitude float,
    speed float,
    gas_level int
);

ALTER TABLE bipol_tracker DISABLE ROW LEVEL SECURITY;

create table if not exists app_info (
    id bigint generated by default as identity primary key,
    title text not null,
    content text not null,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table app_info enable row level security;

create policy "Enable read access for all users"
on app_info for select
using (true);

create policy "Enable insert for authenticated users only"
on app_info for insert
with check (true);

create table if not exists geofences (
    id bigint generated by default as identity primary key,
    name text not null,
    latitude double precision not null,
    longitude double precision not null,
    radius_meters integer default 100,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists geofence_events (
    id bigint generated by default as identity primary key,
    bus_id text not null,
    geofence_id bigint references geofences(id),
    event_type text not null,
    timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into geofences (name, latitude, longitude, radius_meters)
values 
('Halte PNJ', -6.372132, 106.824248, 150),
('Garasi / Pool', -6.368864, 106.833098, 200);

alter table geofences enable row level security;
alter table geofence_events enable row level security;

create policy "Public Read Zones" on geofences for select using (true);
create policy "Public Read Events" on geofence_events for select using (true);
